import{useEffect,useState,type FormEvent,type ReactNode}from'react';import{Navigate,NavLink,Route,Routes,useNavigate}from'react-router-dom';import{AdminApplicationDetail,AdminApplications,AdminAudit,AdminDashboard,AdminLoanDetail,AdminLoans,AdminPayments,AdminReports,AdminSettings,AdminUsers}from'./Admin';import CustomerApplication from'./CustomerApplication';import ProfilePage from'./ProfilePage';import{CustomerLoanDetail,CustomerLoans,CustomerPayments}from'./FinancePages';import{Support}from'./CustomerPages';
const API=import.meta.env.VITE_API_URL||'http://localhost:4000/api';export type User={id:string;email:string;role:'customer'|'admin'|'super_admin';name?:string;mobile?:string;whatsapp?:string;address?:string};
export async function request(path:string,options:RequestInit={}){const token=localStorage.getItem('token');let r:Response;try{r=await fetch(API+path,{...options,headers:{...(options.body instanceof FormData?{}:{'Content-Type':'application/json'}),...(token?{Authorization:`Bearer ${token}`}:{}) as any,...options.headers}})}catch{throw new Error('Cannot connect to the server. Keep npm run dev running and try again.')}const body=await r.json().catch(()=>({}));if(!r.ok){const issue=body.error?.details?.issues?.[0];const field=issue?.path?issue.path.split('.').pop()?.replace(/([A-Z])/g,' $1').toLowerCase():'';throw new Error(issue?(field+': '+issue.message):(body.error?.message||'Request failed'))}return body.data}
export const money=(p:number|string=0)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(p)/100);
function Brand(){return <div className="brand"><span className="brandmark">S</span><span>Saathi<small>FINANCE</small></span></div>}
function Login({onLogin}:{onLogin:(u:User)=>void}){const[mode,setMode]=useState<'login'|'register'>('login'),[error,setError]=useState(''),[busy,setBusy]=useState(false);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const fd=new FormData(e.currentTarget),payload=Object.fromEntries(fd);try{const d=await request('/auth/'+mode,{method:'POST',body:JSON.stringify(payload)});localStorage.setItem('token',d.token);onLogin(d.user)}catch(x){setError((x as Error).message)}finally{setBusy(false)}};return <main className="auth"><section className="welcome"><Brand/><div><span className="eyebrow">BORROW WITH CLARITY</span><h1>Small steps.<br/><em>Stronger tomorrows.</em></h1><p>Understand every rupee, every date, and every decisionâ€”before you accept a loan.</p><div className="trust"><span>âœ“ Transparent terms</span><span>âœ“ Human support</span><span>âœ“ Your data stays private</span></div></div><footer>Responsible lending for real life.</footer></section><section className="authcard"><div className="mobile-brand"><Brand/></div><div className="card"><span className="eyebrow">WELCOME</span><h2>{mode==='login'?'Good to see you':'Create your account'}</h2><p>{mode==='login'?'Sign in to continue to your account.':'Start a secure loan application in minutes.'}</p><form onSubmit={submit}>{mode==='register'&&<><label>Full name<input name="name" required placeholder="Your name"/></label><label>Mobile number<input name="mobile" required placeholder="+91 98765 43210"/></label></>}<label>Email address<input name="email" type="email" required placeholder="you@example.com"/></label><label>Password<input name="password" type="password" minLength={8} required placeholder="At least 8 characters"/></label>{error&&<div className="alert">{error}</div>}<button className="primary" disabled={busy}>{busy?'Please waitâ€¦':mode==='login'?'Sign in securely':'Create account'}</button></form><button className="text" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'New to Saathi? Create an account':'Already registered? Sign in'}</button><p className="secure">ðŸ”’ Protected with secure encryption</p></div></section></main>}
function Shell({user,onLogout,children}:{user:User;onLogout:()=>void;children:ReactNode}){const admin=user.role!=='customer';const links=admin?[['/admin','Overview','⌂'],['/admin/applications','Applications','▤'],['/admin/loans','Loans','₹'],['/admin/payments','Payments','↗'],['/admin/reports','Reports','▥'],['/admin/settings','Settings','⚙'],...(user.role==='super_admin'?[['/admin/users','Admins','♙'],['/admin/audit','Audit','≡']]:[])]:[['/','Home','⌂'],['/apply','Apply','＋'],['/loans','My loans','₹'],['/payments','Payments','↗'],['/profile','Profile','○']];return <div className="shell"><aside><Brand/><nav>{links.map(([to,label,icon])=><NavLink key={to} to={to} end={to==='/'||to==='/admin'}><span>{icon}</span>{label}</NavLink>)}</nav><button className="logout" onClick={onLogout}>Sign out</button></aside><header><Brand/><div className="avatar">{(user.name||user.email)[0].toUpperCase()}</div></header><div className="content">{children}</div><nav className="bottom">{links.slice(0,5).map(([to,label,icon])=><NavLink key={to} to={to} end={to==='/'||to==='/admin'}><span>{icon}</span><small>{label}</small></NavLink>)}</nav></div>}
function CustomerHome({user}:{user:User}){const[apps,setApps]=useState<any[]>([]),[loans,setLoans]=useState<any[]>([]);useEffect(()=>{request('/applications').then(setApps);request('/loans').then(setLoans)},[]);const active=loans[0];return <><div className="pagehead"><div><span className="eyebrow">YOUR FINANCIAL SPACE</span><h1>Hello, {(user.name||'friend').split(' ')[0]}.</h1><p>Hereâ€™s where everything stands today.</p></div><NavLink className="primary small" to="/apply">New application</NavLink></div>{active?<section className="hero-card"><div><span className="status">â— {active.status.replace('_',' ')}</span><p>Outstanding balance</p><h2>{money(Number(active.total_due_paise)-Number(active.paid_paise))}</h2></div><div className="due"><small>NEXT PAYMENT</small><strong>{active.next_due_date||'All paid'}</strong><span>View repayment schedule â†’</span></div></section>:<section className="empty-feature"><div><span className="eyebrow">A FRESH START</span><h2>A loan you can understand.</h2><p>Clear terms, predictable instalments, and no hidden surprises. Check your options without pressure.</p><NavLink className="primary" to="/apply">Start an application</NavLink></div><div className="sun">â‚¹</div></section>}<h3 className="section-title">Your applications</h3><div className="cards">{apps.length?apps.map(a=><NavLink className="list-card" to={`/applications/${a.id}`} key={a.id}><div><span className={`pill ${a.status}`}>{a.status.replace('_',' ')}</span><h3>{money(a.requested_amount_paise)}</h3><p>{a.purpose}</p></div><span>â€º</span></NavLink>):<div className="empty">No applications yet. Your saved drafts and submitted requests will appear here.</div>}</div><section className="help"><span>?</span><div><strong>Need a hand?</strong><p>Our support team can explain the process in Hindi or English.</p></div><NavLink to="/support">Contact support</NavLink></section></>}
const initial={name:'',dateOfBirth:'',guardianName:'',mobile:'',whatsapp:'',address:'',monthlyIncome:'',purpose:'',amount:'',kin:'',relationship:'',bank:'',holder:'',ifsc:'',account:'',w1name:'',w1guardian:'',w1mobile:'',w1address:'',w2name:'',w2guardian:'',w2mobile:'',w2address:''};
function Apply(){const[step,setStep]=useState(0),[f,setF]=useState<any>(()=>JSON.parse(localStorage.getItem('loan-draft')||JSON.stringify(initial))),[error,setError]=useState(''),nav=useNavigate();const set=(k:string,v:string)=>setF({...f,[k]:v});const save=()=>{localStorage.setItem('loan-draft',JSON.stringify(f));setError('Draft saved on this device.')};const fillDemo=()=>{const demo={name:'Ananya Sharma',dateOfBirth:'1994-06-18',guardianName:'Rajesh Sharma',mobile:'9876543210',whatsapp:'9876543210',address:'24 Sample Nagar, Demo Road, Jaipur, Rajasthan 302001',monthlyIncome:'45000',purpose:'Small business equipment purchase',amount:'150000',kin:'Meera Sharma',relationship:'Mother',bank:'Demo National Bank',holder:'Ananya Sharma',ifsc:'SBIN0001234',account:'123456789012',w1name:'Neha Verma',w1guardian:'Suresh Verma',w1mobile:'9811111111',w1address:'18 Sample Colony, Jaipur, Rajasthan 302002',w2name:'Arjun Mehta',w2guardian:'Ramesh Mehta',w2mobile:'9822222222',w2address:'42 Demo Park, Jaipur, Rajasthan 302003'};setF(demo);localStorage.setItem('loan-draft',JSON.stringify(demo));setStep(0);setError('Demo data filled. Review every field before continuing. This does not submit the application.')};
const submit=async()=>{try{const a=await request('/applications',{method:'POST',body:JSON.stringify({customer:{name:f.name,dateOfBirth:f.dateOfBirth,guardianName:f.guardianName,mobile:f.mobile,whatsapp:f.whatsapp,address:f.address,identifierType:'none'},witnesses:[{name:f.w1name,guardianName:f.w1guardian,mobile:f.w1mobile,address:f.w1address},{name:f.w2name,guardianName:f.w2guardian,mobile:f.w2mobile,address:f.w2address}],loan:{monthlyIncomePaise:Math.round(Number(f.monthlyIncome)*100),purpose:f.purpose,requestedAmountPaise:Math.round(Number(f.amount)*100),nextOfKinName:f.kin,nextOfKinRelationship:f.relationship},bank:{bankName:f.bank,accountHolderName:f.holder,ifsc:f.ifsc.replace(/\s/g,'').toUpperCase(),accountNumber:f.account},consent:true})});await request(`/applications/${a.id}/submit`,{method:'POST'});localStorage.removeItem('loan-draft');nav('/')}catch(e){setError((e as Error).message)}};const requiredByStep=[['name','dateOfBirth','guardianName','mobile','whatsapp','address'],['monthlyIncome','amount','purpose','kin','relationship'],['w1name','w1guardian','w1mobile','w1address','w2name','w2guardian','w2mobile','w2address'],['bank','holder','ifsc','account']];const next=()=>{const missing=(requiredByStep[step]||[]).filter(k=>!String(f[k]||'').trim());if(missing.length){setError('Please complete every field on this step before continuing.');return}if(step===0&&String(f.address).trim().length<10){setError('Residential address must be at least 10 characters.');return}if(step===1&&(Number(f.monthlyIncome)<=0||Number(f.amount)<=0)){setError('Monthly income and requested amount must be greater than zero.');return}if(step===2&&(String(f.w1address).trim().length<10||String(f.w2address).trim().length<10)){setError('Both witness addresses must be at least 10 characters.');return}if(step===3&&!/^[A-Za-z]{4}0[A-Za-z0-9]{6}$/.test(String(f.ifsc).replace(/\s/g,''))){setError('Enter a valid 11-character IFSC, for example SBIN0001234.');return}setError('');setStep(step+1)};const fields=(items:string[][])=>items.map(([k,l,t='text'])=><label key={k}>{l}<input type={t} value={f[k]} onChange={e=>set(k,e.target.value)} required/></label>);return <><div className="pagehead">
<div><span className="eyebrow">LOAN APPLICATION</span><h1>Tell us what you need.</h1><p>Step {step+1} of 5 Â· You can save and return anytime.</p></div>
<button type="button" className="demo-fill" onClick={fillDemo}><span>DEMO</span><div><strong>Fill demo data</strong><small>Populate all fields for testing</small></div></button>
</div>
<div className="progress"><i style={{width:`${(step+1)*20}%`}}/></div><section className="form-card"><div className="step-label">{['About you','Loan details','Witnesses','Bank details','Review'][step]}</div>{step===0&&<div className="form-grid">{fields([['name','Full name'],['dateOfBirth','Date of birth','date'],['guardianName',"Fatherâ€™s or husbandâ€™s name"],['mobile','Mobile number','tel'],['whatsapp','WhatsApp number','tel'],['address','Residential address']])}</div>}
{step===1&&<div className="form-grid">{fields([['monthlyIncome','Monthly income (â‚¹)','number'],['amount','Requested amount (â‚¹)','number'],['purpose','Loan purpose'],['kin','Next-of-kin name'],['relationship','Relationship']])}</div>}
{step===2&&<><div className="note">Witnesses confirm familiarity with you. They are not automatically guarantors and are not made liable for repayments.</div><h3>Witness 1</h3><div className="form-grid">{fields([['w1name','Name'],['w1guardian',"Fatherâ€™s name"],['w1mobile','Mobile / WhatsApp'],['w1address','Address']])}</div><h3>Witness 2</h3><div className="form-grid">{fields([['w2name','Name'],['w2guardian',"Fatherâ€™s name"],['w2mobile','Mobile / WhatsApp'],['w2address','Address']])}</div></>}
{step===3&&<><div className="note">Your bank details are encrypted and masked in ordinary views. Transfers are completed manually after approval.</div><div className="form-grid">{fields([['bank','Bank name'],['holder','Account holder name'],['ifsc','IFSC'],['account','Account number']])}</div></>}
{step===4&&<div className="review"><h2>Please review carefully</h2><p><strong>{f.name}</strong> is requesting <strong>{money(Number(f.amount)*100)}</strong> for {f.purpose}.</p><p>Bank: {f.bank} Â· account ending {f.account.slice(-4)}</p><p>Witness 1: {f.w1name}<br/>Witness 2: {f.w2name}</p><div className="note">Submitting confirms the information is accurate. This is an application, not a loan agreement or guarantee of approval.</div></div>}{error&&<div className="alert">{error}</div>}<div className="actions"><button className="secondary" onClick={save}>Save draft</button>{step>0&&<button className="secondary" onClick={()=>setStep(step-1)}>Back</button>}{step<4?<button className="primary" onClick={next}>Continue</button>:<button className="primary" onClick={submit}>Submit application</button>}</div></section></>}
function Loans(){const[loans,setLoans]=useState<any[]>([]);useEffect(()=>{request('/loans').then(setLoans)},[]);return <><div className="pagehead"><div><span className="eyebrow">REPAYMENT</span><h1>My loans</h1><p>Confirmed balances and upcoming dates.</p></div></div><div className="cards">{loans.map(l=><article className="loan-card" key={l.id}><span className="pill">{l.status}</span><h2>{money(Number(l.total_due_paise)-Number(l.paid_paise))}</h2><p>Outstanding Â· {money(l.paid_paise)} paid</p><div className="meter"><i style={{width:`${Number(l.total_due_paise)?Number(l.paid_paise)/Number(l.total_due_paise)*100:0}%`}}/></div><small>Next due: {l.next_due_date||'â€”'}</small></article>)}{!loans.length&&<div className="empty">You do not have a disbursed loan yet.</div>}</div></>}
function AdminHome(){const[d,setD]=useState<any>({});useEffect(()=>{request('/admin/dashboard').then(setD)},[]);return <><div className="pagehead"><div><span className="eyebrow">PILOT OPERATIONS</span><h1>Good morning.</h1><p>Hereâ€™s what needs attention today.</p></div><span className="date">LIVE OVERVIEW</span></div><div className="stats">{[['New applications',d.new_applications||0,'Review queue'],['Pending reviews',d.pending_reviews||0,'In progress'],['Awaiting transfer',d.awaiting_disbursement||0,'Record manually'],['Overdue EMIs',d.overdue_emis||0,'Needs attention']].map(([l,v,s],i)=><article key={l as string} className={i===3?'warn':''}><span>{l}</span><strong>{v}</strong><small>{s}</small></article>)}</div><section className="panel"><div className="panel-title"><div><span className="eyebrow">NEXT ACTIONS</span><h2>Keep the queue moving</h2></div><NavLink to="/admin/applications">View all applications â†’</NavLink></div><div className="action-grid"><div><b>01</b><h3>Review submitted applications</h3><p>Verify customer, witnesses, documents, and bank details.</p></div><div><b>02</b><h3>Confirm accepted offers</h3><p>Record transfers only after funds actually leave the bank.</p></div><div><b>03</b><h3>Reconcile repayments</h3><p>EMIs update only after payments are confirmed.</p></div></div></section></>}
function Applications(){const[rows,setRows]=useState<any[]>([]),[status,setStatus]=useState('');useEffect(()=>{request('/applications'+(status?`?status=${status}`:'')).then(setRows)},[status]);return <><div className="pagehead"><div><span className="eyebrow">APPLICATION QUEUE</span><h1>Applications</h1><p>Review and move each case deliberately.</p></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>submitted</option><option>under_review</option><option>information_requested</option><option>approved</option><option>rejected</option></select></div><div className="table"><div className="tr th"><span>Applicant</span><span>Requested</span><span>Status</span><span>Received</span></div>{rows.map(r=><div className="tr" key={r.id}><span><strong>{r.name}</strong><small>{r.mobile}</small></span><span>{money(r.requested_amount_paise)}</span><span><i className={`pill ${r.status}`}>{r.status.replace('_',' ')}</i></span><span>{new Date(r.created_at).toLocaleDateString('en-IN')}</span></div>)}{!rows.length&&<div className="empty">No applications match this filter.</div>}</div></>}
function Placeholder({title,text}:{title:string;text:string}){return <div className="empty-page"><span className="eyebrow">SAATHI FINANCE</span><h1>{title}</h1><p>{text}</p></div>}
export default function App(){const[user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(!!localStorage.getItem('token'));useEffect(()=>{if(localStorage.getItem('token'))request('/me').then(setUser).catch(()=>localStorage.removeItem('token')).finally(()=>setLoading(false))},[]);if(loading)return <div className="splash"><Brand/><span>Loading securelyâ€¦</span></div>;if(!user)return <Login onLogin={setUser}/>;const admin=user.role!=='customer';return <Shell user={user} onLogout={()=>{localStorage.removeItem('token');setUser(null)}}>
<Routes>{admin?<>
<Route path="/admin" element={<AdminDashboard/>}/>
<Route path="/admin/applications" element={<AdminApplications/>}/>
<Route path="/admin/applications/:id" element={<AdminApplicationDetail/>}/>
<Route path="/admin/loans" element={<AdminLoans/>}/>
<Route path="/admin/loans/:id" element={<AdminLoanDetail/>}/>
<Route path="/admin/payments" element={<AdminPayments/>}/>
<Route path="/admin/reports" element={<AdminReports/>}/>
<Route path="/admin/settings" element={<AdminSettings user={user}/>}/>
<Route path="/admin/users" element={<AdminUsers user={user}/>}/>
<Route path="/admin/audit" element={<AdminAudit user={user}/>}/>
<Route path="*" element={<Navigate to="/admin"/>}/></>:<>
<Route path="/" element={<CustomerHome user={user}/>}/>
<Route path="/apply" element={<Apply/>}/>
<Route path="/applications/:id" element={<CustomerApplication/>}/>
<Route path="/loans" element={<CustomerLoans/>}/>
<Route path="/loans/:id" element={<CustomerLoanDetail/>}/>
<Route path="/payments" element={<CustomerPayments/>}/>
<Route path="/profile" element={<ProfilePage user={user} onUpdate={setUser} onLogout={()=>{localStorage.removeItem('token');setUser(null)}}/>}/>
<Route path="/support" element={<Support/>}/>
<Route path="*" element={<Navigate to="/"/>}/></>}</Routes></Shell>}
