import {useEffect,useState,type FormEvent} from 'react';
import {Link,useParams} from 'react-router-dom';
import {money,request,type User} from './App';

const Message=({value}:{value:string})=>value?<div className="alert" role="status">{value}</div>:null;

export function CustomerLoans(){const[rows,setRows]=useState<any[]>([]),[error,setError]=useState('');useEffect(()=>{request('/loans').then(setRows).catch(e=>setError(e.message))},[]);return <><div className="pagehead"><div><span className="eyebrow">REPAYMENT</span><h1>My loans</h1><p>Confirmed balances, transfer details, and upcoming dates.</p></div></div><Message value={error}/><div className="cards">{rows.map(l=><Link className="loan-card customer-loan-link" to={`/loans/${l.id}`} key={l.id}><span className="pill">{l.status.replaceAll('_',' ')}</span><h2>{money(Number(l.total_due_paise)-Number(l.paid_paise))}</h2><p>Outstanding · {money(l.paid_paise)} confirmed paid</p><div className="meter"><i style={{width:`${Number(l.total_due_paise)?Math.min(100,Number(l.paid_paise)/Number(l.total_due_paise)*100):0}%`}}/></div><small>Next due: {l.next_due_date||'All paid'} · View full details →</small></Link>)}{!rows.length&&!error&&<div className="empty">You do not have a disbursed loan yet.</div>}</div></>}

export function CustomerLoanDetail(){const{id}=useParams(),[loan,setLoan]=useState<any>(null),[error,setError]=useState('');useEffect(()=>{request(`/loans/${id}`).then(setLoan).catch(e=>setError(e.message))},[id]);if(!loan)return <div className="empty">{error||'Loading loan…'}</div>;const paid=loan.schedule.reduce((sum:number,row:any)=>sum+Number(row.paid_paise),0),total=Number(loan.total_payable_paise),transfer=loan.disbursements[0];return <><div className="pagehead"><div><Link className="back" to="/loans">← My loans</Link><h1>Loan details</h1><p>Only confirmed transfers and payments are reflected here.</p></div><i className="pill">{loan.status.replaceAll('_',' ')}</i></div><div className="stats"><article><span>Total payable</span><strong>{money(total)}</strong><small>Accepted terms</small></article><article><span>Confirmed paid</span><strong>{money(paid)}</strong><small>Allocated to EMIs</small></article><article><span>Outstanding</span><strong>{money(total-paid)}</strong><small>Derived balance</small></article><article><span>Next due</span><strong className="date-value">{loan.schedule.find((x:any)=>Number(x.paid_paise)<Number(x.total_due_paise))?.due_date||'All paid'}</strong><small>Monthly schedule</small></article></div>{transfer&&<section className="panel"><h2>Disbursement</h2><dl><dt>Amount transferred</dt><dd>{money(transfer.amount_paise)}</dd><dt>Transfer date</dt><dd>{transfer.transfer_date}</dd><dt>Bank reference / UTR</dt><dd>{transfer.bank_reference}</dd></dl></section>}<section className="panel admin-section"><h2>EMI schedule</h2><div className="schedule"><div className="schedule-row head"><span># / Due</span><span>Principal</span><span>Interest + fees</span><span>Paid / due</span></div>{loan.schedule.map((x:any)=><div className="schedule-row" key={x.id}><span><b>{x.number}</b><small>{x.due_date}</small></span><span>{money(x.principal_paise)}</span><span>{money(Number(x.interest_paise)+Number(x.fees_paise))}</span><span>{money(x.paid_paise)} / {money(x.total_due_paise)}</span></div>)}</div></section><section className="panel admin-section"><h2>Payment history</h2>{loan.payments.map((x:any)=><div className="line" key={x.id}><span><strong>{x.payment_date}</strong><small>{x.method.replaceAll('_',' ')} · {x.reference}</small></span><span>{money(x.amount_paise)} <i className="pill">{x.status.replaceAll('_',' ')}</i></span></div>)}{!loan.payments.length&&<p className="muted">No payments have been recorded.</p>}</section></>}

export function CustomerPayments(){const[rows,setRows]=useState<any[]>([]),[error,setError]=useState('');useEffect(()=>{request('/payments').then(setRows).catch(e=>setError(e.message))},[]);return <><div className="pagehead"><div><span className="eyebrow">PAYMENT HISTORY</span><h1>Payments</h1><p>Only confirmed payments reduce your outstanding balance.</p></div></div><Message value={error}/><div className="table"><div className="tr th"><span>Date / reference</span><span>Amount</span><span>Method</span><span>Status</span></div>{rows.map(x=><Link to={`/loans/${x.loan_id}`} className="tr row-link" key={x.id}><span><strong>{x.payment_date}</strong><small>{x.reference}</small></span><span>{money(x.amount_paise)}</span><span>{x.method.replaceAll('_',' ')}</span><span><i className="pill">{x.status.replaceAll('_',' ')}</i></span></Link>)}{!rows.length&&!error&&<div className="empty">No payments have been recorded yet.</div>}</div></>}

export function CustomerProfile({user,onUpdate}:{user:User;onUpdate:(user:User)=>void}){const[form,setForm]=useState<any>(user),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMessage('');try{const updated=await request('/me',{method:'PATCH',body:JSON.stringify(form)});setForm(updated);onUpdate(updated);setMessage('Profile saved successfully.')}catch(x){setMessage((x as Error).message)}finally{setBusy(false)}};return <><div className="pagehead"><div><span className="eyebrow">YOUR ACCOUNT</span><h1>Profile</h1><p>Keep your contact information current.</p></div></div><section className="panel"><form onSubmit={submit}><div className="form-grid"><label>Full name<input required value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email address<input disabled value={form.email||''}/></label><label>Mobile number<input required value={form.mobile||''} onChange={e=>setForm({...form,mobile:e.target.value})}/></label><label>WhatsApp number<input value={form.whatsapp||''} onChange={e=>setForm({...form,whatsapp:e.target.value})}/></label><label className="wide">Residential address<input value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/></label></div><Message value={message}/><div className="actions"><button className="primary" disabled={busy}>{busy?'Saving…':'Save profile'}</button></div></form></section><section className="panel admin-section"><h2>Privacy</h2><p className="muted">Your application, identity, bank, and witness information is private. Bank account numbers are masked in ordinary views. Contact support for access or deletion requests under the lender’s retention policy.</p></section></>}

export function Support(){const[data,setData]=useState<any>(null),[error,setError]=useState('');useEffect(()=>{request('/settings/public').then(setData).catch(e=>setError(e.message))},[]);return <><div className="pagehead"><div><span className="eyebrow">HELP & GRIEVANCE</span><h1>We’re here to help</h1><p>Ask about an application, offer, payment, or privacy request.</p></div></div><Message value={error}/><div className="detail-grid"><section className="panel"><h2>Customer support</h2><p className="muted">Our team can explain the process in Hindi or English. Support cannot promise approval or mark an unconfirmed payment as paid.</p><dl><dt>Phone</dt><dd><a href={`tel:${data?.phone||''}`}>{data?.phone||'Loading…'}</a></dd><dt>Email</dt><dd><a href={`mailto:${data?.email||''}`}>{data?.email||'Loading…'}</a></dd></dl></section><section className="panel"><h2>Grievance contact</h2><p className="muted">For unresolved complaints, include your application or loan ID, but never send your password or full bank account number.</p><dl><dt>Email</dt><dd><a href={`mailto:${data?.grievance||''}`}>{data?.grievance||'Loading…'}</a></dd></dl></section></div></>}
