import {useEffect,useState} from 'react';
import {Link,useNavigate,useParams} from 'react-router-dom';
import {money,request} from './App';
import ApplicationDocuments from './ApplicationDocuments';
import './application-status.css';
import './customer-activity.css';

export default function CustomerApplication(){
  const{id}=useParams(),navigate=useNavigate();
  const[application,setApplication]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const load=async()=>{try{setApplication(await request(`/applications/${id}`))}catch(e){setError((e as Error).message)}};
  useEffect(()=>{load();const timer=window.setInterval(load,15000);const refresh=()=>{if(document.visibilityState==='visible')load()};document.addEventListener('visibilitychange',refresh);return()=>{window.clearInterval(timer);document.removeEventListener('visibilitychange',refresh)}},[id]);
  const accept=async(offerId:string)=>{if(!confirm('Accept this offer after reviewing the complete cost and repayment schedule?'))return;setBusy(true);setError('');try{await request(`/offers/${offerId}/accept`,{method:'POST'});await load();navigate('/loans')}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
  if(!application)return <div className="empty">{error||'Loading application…'}</div>;
  const offer=application.offers?.find((x:any)=>x.status==='presented'),latestMessage=[...(application.reviews||[])].reverse().find((x:any)=>x.message)?.message;
  return <main className="application-detail"><div className="pagehead"><div><Link className="back" to="/">← Home</Link><h1>Loan application</h1><p>{application.submitted_at?`Submitted ${new Date(application.submitted_at).toLocaleDateString('en-IN')}`:'Draft application'}</p></div><i className={`pill ${application.status}`}>{application.status.replaceAll('_',' ')}</i></div>{error&&<div className="alert" role="status">{error}</div>}<ApplicationStatus application={application}/><CustomerActivity application={application}/>
{latestMessage&&<div className="customer-review-message"><span>Message from the review team</span><p>{latestMessage}</p></div>}<section className="panel"><dl><dt>Requested amount</dt><dd>{money(application.requested_amount_paise)}</dd><dt>Loan purpose</dt><dd>{application.purpose}</dd><dt>Application ID</dt><dd>{application.id.slice(0,8).toUpperCase()}</dd></dl></section><ApplicationDocuments applicationId={application.id} documents={application.documents||[]} onUploaded={load}/>{offer?<Offer offer={offer} busy={busy} onAccept={accept}/>:<section className="panel admin-section"><h2>No offer awaiting acceptance</h2><p className="muted">If your application is approved, the complete pricing, charges, and EMI schedule will appear here for review before you decide.</p></section>}</main>
}

const statusCopy:any={draft:['Draft saved','Complete and submit your application when ready.'],submitted:['Application submitted','Your application is in the queue and waiting for the review team.'],under_review:['Your application is under review','An administrator has started checking your information and documents. No action is required unless we contact you.'],information_requested:['Information required','The review team needs a correction or additional information. Read the message below and update the requested details.'],approved:['Application approved','Your application has been approved. Review the complete offer when it is presented before accepting.'],rejected:['Application not approved','The review is complete. Contact support if you need help understanding the decision.'],withdrawn:['Application withdrawn','This application is no longer active.']};
function ApplicationStatus({application}:{application:any}){const current=application.status,[title,description]=statusCopy[current]||['Application updated','Check the latest application information below.'],events=application.reviews||[],last=events[events.length-1],normal=['submitted','under_review','approved'],terminal=current==='rejected'||current==='withdrawn',currentIndex=normal.indexOf(current);return <section className={`customer-status-card status-${current}`}><div className="customer-status-heading"><span className="status-symbol">{current==='under_review'?'↻':current==='approved'?'✓':current==='information_requested'?'!':terminal?'×':'•'}</span><div><small>APPLICATION STATUS</small><h2>{title}</h2><p>{description}</p>{last&&<time>Updated {new Date(last.created_at).toLocaleString('en-IN')}</time>}</div><b>Live status</b></div><div className="customer-progress">{normal.map((status,index)=><div className={`${index<currentIndex?'done':''} ${status===current?'current':''}`} key={status}><i>{index<currentIndex||status===current&&current==='approved'?'✓':index+1}</i><span>{status.replaceAll('_',' ')}</span></div>)}{(current==='information_requested'||terminal)&&<div className="current exception"><i>{terminal?'×':'!'}</i><span>{current.replaceAll('_',' ')}</span></div>}</div></section>}

const actionText:any={under_review:['Review started','The review team started checking your application.'],information_requested:['Information requested','The review team requested a correction or additional information.'],approved:['Application approved','The review team approved your application.'],rejected:['Application not approved','The review team completed the review without approval.'],withdrawn:['Application withdrawn','The application was withdrawn.']};
function CustomerActivity({application}:{application:any}){const events:any[]=[];if(application.submitted_at)events.push({action:'submitted',title:'Application submitted',text:'Your application was received successfully.',at:application.submitted_at});for(const review of application.reviews||[]){const copy=actionText[review.action]||[review.action.replaceAll('_',' '),'Application status updated.'];events.push({action:review.action,title:copy[0],text:review.message||copy[1],at:review.created_at})}for(const offer of application.offers||[]){if(offer.presented_at)events.push({action:'offer',title:'Loan offer presented',text:'Complete pricing and the EMI schedule are ready for your review.',at:offer.presented_at});if(offer.accepted_at)events.push({action:'accepted',title:'Offer accepted',text:'Your accepted loan is awaiting a confirmed manual bank transfer.',at:offer.accepted_at})}events.sort((a,b)=>String(b.at).localeCompare(String(a.at)));return <section className="customer-activity"><div className="customer-activity-head"><div><span>APPLICATION ACTIVITY</span><h2>Updates from the review team</h2></div><small>{events.length} updates</small></div><div className="customer-activity-list">{events.map((event,index)=><article key={`${event.action}-${event.at}-${index}`}><i className={`activity-dot ${event.action}`}>{index===0?'✓':''}</i><div><strong>{event.title}</strong><p>{event.text}</p><time>{new Date(event.at).toLocaleString('en-IN')}</time></div>{index===0&&<b>Latest</b>}</article>)}</div></section>}

function Offer({offer,busy,onAccept}:{offer:any;busy:boolean;onAccept:(id:string)=>void}){return <section className="panel admin-section offer-customer"><span className="eyebrow">LOAN OFFER</span><h2>Review the complete cost before accepting</h2><div className="preview"><div><small>Principal</small><strong>{money(offer.terms.principalPaise)}</strong></div><div><small>Total interest</small><strong>{money(offer.total_interest_paise)}</strong></div><div><small>Total payable</small><strong>{money(offer.total_payable_paise)}</strong></div></div><dl><dt>Interest rate</dt><dd>{offer.terms.rate}% {offer.terms.ratePeriod}</dd><dt>Calculation method</dt><dd>{offer.terms.method.replaceAll('_',' ')}</dd><dt>Instalments</dt><dd>{offer.terms.instalments} monthly</dd><dt>First due date</dt><dd>{offer.terms.firstDueDate}</dd><dt>Processing fee</dt><dd>{money(offer.terms.processingFeePaise)}</dd><dt>Other charges</dt><dd>{money(offer.terms.otherChargesPaise)}</dd></dl><div className="schedule customer-schedule"><div className="schedule-row head"><span># / Due</span><span>Principal</span><span>Interest + fees</span><span>Total due</span></div>{offer.schedule_snapshot.map((row:any)=><div className="schedule-row" key={row.number}><span><b>{row.number}</b><small>{row.dueDate}</small></span><span>{money(row.principalPaise)}</span><span>{money(row.interestPaise+row.feesPaise)}</span><span>{money(row.totalDuePaise)}</span></div>)}</div><div className="note">Accepting creates a loan awaiting manual bank disbursement. It does not mean funds have already been transferred.</div><div className="actions"><button className="primary" disabled={busy} onClick={()=>onAccept(offer.id)}>{busy?'Accepting…':'Accept this offer'}</button></div></section>}
